const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const base=process.argv[2]||'http://127.0.0.1:8769';
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.P109_BROWSER||'chrome'});
  const page=await browser.newPage({viewport:{width:1440,height:1100}});
  const other=await browser.newPage({viewport:{width:1440,height:1100}});
  const errors=[],failed=[];
  for(const p of [page,other]) {p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400) failed.push([r.status(),r.url()]);});}
  const action=(p,name)=>p.locator(`[data-action="${name}"]`);
  const saved=async id=>(await (await page.request.get(base+'/api/complaints/'+id)).json()).complaint;
  try {
    await page.goto(base+'/#routing');
    await page.getByText('1600',{exact:true}).waitFor();
    await page.locator('#health-region').selectOption('KZ-SHY');
    await page.locator('.health-table tbody tr').first().getByText('город Шымкент',{exact:true}).waitFor();
    assert.ok((await page.locator('.health-table tbody tr td:nth-child(2)').allTextContents()).every(x=>x==='город Шымкент'));
    const health=await (await page.request.get(base+'/api/workspace/routing-health')).json();
    assert.equal(health.summary.total,1600);assert.equal(health.summary.uncovered,0);
    assert.ok(health.summary.fallback>0 && health.summary.primary>0);
    console.log('PASS SUPPORT UI 1: 1600 structural routes; region filter leaves global counters intact');
    await page.locator('[data-nav="operators"]').click();
    assert.equal(await page.locator('.operator-card').count(),7);
    await page.locator('.operator-card').filter({hasText:'Данияр'}).getByText(/Перегружен/).waitFor();
    await page.locator('[data-nav="queue"]').click();await action(page,'demo').click();
    await page.locator('#presence-operator').waitFor();
    const id=await page.locator('#case-title').innerText();
    await page.locator('.routing-alternatives summary').click();
    await page.locator('.routing-alternatives').getByText(/Слоты заняты: 7\/6/).waitFor();
    await page.locator('.routing-alternatives').getByText(/Статус: away/).waitFor();
    console.log('PASS SUPPORT UI 2: seven operators; workload, overloaded and offline alternatives visible');
    await page.locator('#presence-operator').selectOption('op-aidana');
    await other.goto(base);
    await other.getByRole('searchbox',{name:'Поиск обращений'}).fill(id);
    await other.locator(`.queue-row[data-id="${id}"]`).click();
    await other.locator('#presence-operator').selectOption('op-timur');
    await other.locator('#reply-text').fill('Демо: ответ второго оператора.');
    await page.locator('#reply-text').fill('Мой несохранённый черновик');
    await page.locator('#presence-peers').filter({hasText:/Тимур.*редактирует/}).waitFor();
    await action(other,'save-reply').click();
    await page.locator('#case-changed').waitFor();
    assert.equal(await page.locator('#reply-text').inputValue(),'Мой несохранённый черновик');
    await page.locator('#case-changed [data-action="reload-case"]').click();
    await page.locator('.timeline').getByText('Демо: ответ второго оператора.',{exact:true}).waitFor();
    assert.equal(await page.locator('#reply-text').inputValue(),'Мой несохранённый черновик');
    await action(other,'close').click();
    await page.locator('#presence-peers').filter({hasText:'Других операторов'}).waitFor();
    console.log('PASS SUPPORT UI 3: two sessions, editing indicator, saved-change notice; draft survives refresh');
    await page.keyboard.press('Control+k');
    await page.locator('#command-search').fill('приоритет');
    assert.equal(await page.locator('.command-option').count(),2);
    await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
    await page.locator('#playbook-dialog').waitFor();
    assert.equal((await saved(id)).decision_status,'pending');
    await page.getByRole('button',{name:'Отмена',exact:true}).click();
    assert.equal((await saved(id)).priority,null);
    await page.keyboard.press('Meta+k');
    await page.locator('#command-search').fill('приоритет');
    await page.locator('[data-command="urgent"]').click();
    await action(page,'execute-playbook').click();
    await page.locator('#playbook-dialog').waitFor({state:'hidden'});
    await page.getByRole('button',{name:'Решение подтверждено',exact:true}).waitFor();
    assert.equal((await saved(id)).priority,'urgent');
    if(process.argv[3]) await page.screenshot({path:path.join(process.argv[3],'pulse109-routing-presence.png')});
    assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
    console.log('PASS SUPPORT UI 4: Ctrl/Cmd+K, keyboard search, cancel without mutation, confirmed urgent route');
    console.log('ALL 4 SUPPORT UI CHECKS PASSED');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
